### ISSUE TITLE
feat: 全局配置项设置

### ISSUE THREAD

**Issue by jwcesign** [opennaslab/kubespider#112]
## Ask your question here:
大家讨论下配置项：
1. 代理
2. 周期时间
3. 服务端口
4. 目前我看有人在公网用，设置一下密码认证？

是否还有其他的？
@qingchoulove @xiaozhikang0916 @miRemid @ijwstl

**Comment by manduted** [comment]
前3项。不太关注。第4我觉得可以。。因为我就是挂公网。虽然VPN安全也行。我还有几个同学。。懒得教他们怎么弄VPN。

**Comment by qingchoulove** [comment]
我也觉着添加简单认证，例如BA认证是Ok的。方便直接暴露在公网使用。

**Comment by heywalter** [comment]
公网需求+1

**Comment by richardli1598** [comment]
finished
