### ISSUE TITLE
main.sh 脚本执行闪屏

### ISSUE THREAD

**Issue by qingchoulove** [opennaslab/kubespider#221]
![2023-06-14 11 05 50](https://github.com/opennaslab/kubespider/assets/9648420/e7f99a3b-0383-45dd-b4d4-55cf7811ea0f)

我这执行脚本会一直闪屏，麻烦大佬帮忙看下是什么问题呢？

@DDSDerek

mac系统和QNAP都有这个问题。

**Comment by DDSDerek** [comment]
> ![2023-06-14 11 05 50](https://user-images.githubusercontent.com/9648420/246988126-e7f99a3b-0383-45dd-b4d4-55cf7811ea0f.gif)
> 
> 我这执行脚本会一直闪屏，麻烦大佬帮忙看下是什么问题呢？
> 
> @DDSDerek
> 
> mac系统和QNAP都有这个问题。

是不是因为这些系统没有read -ep这个选项？

**Comment by DDSDerek** [comment]
我看着像是输入的内容错误造成一直循环

**Comment by qingchoulove** [comment]
好像发现问题了，我问了下chatgpt ，因为我尝试使用 curl -sSL  <main.sh> |bash 来执行脚本。因为需要交互输入方式在管道执行时会有问题。大佬看下这个是否有解决方法呢？还是我的使用有问题。

**Comment by DDSDerek** [comment]
是使用问题，到时候我会写docs的，现在功能还没有完成
