### ISSUE TITLE
container detection is specific to docker

### ISSUE THREAD

**Issue by qingchoulove** [opennaslab/kubespider#231]
containerd as the container runtime, but the container detection method used in #225 is not working anymore.
```
FileNotFoundError: [Errno 2] No such file or directory: '/.config/source_provider.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/kubespider/app.py", line 8, in <module>
    main()
  File "/app/kubespider/app.py", line 5, in main
    runner.run_with_config_handler()
  File "/app/kubespider/core/runner.py", line 34, in run_with_config_handler
    config_handler.prepare_config()
  File "/app/kubespider/core/config_handler.py", line 177, in prepare_config
    raise Exception(str('failed to copy %s to %s:%s', template_cfg, target_cfg)) from err
TypeError: decoding str is not supported

```

**Comment by ljtnono** [comment]
@qingchoulove 这里可能是我思路有问题，不应该这样判断是开发环境还是容器运行环境。后面想了下，是不是可以通过判断.git文件夹是否存在来判断是开发还是容器运行环境？

**Comment by qingchoulove** [comment]
> @qingchoulove 这里可能是我思路有问题，不应该这样判断是开发环境还是容器运行环境。后面想了下，是不是可以通过判断.git文件夹是否存在来判断是开发还是容器运行环境？

我在dockerfile手动创建了 `/.dockerenv`，这样来保证容器运行环境可以正确检测，稍候发出PR辛苦大佬也看下。

**Comment by ljtnono** [comment]
@qingchoulove 我觉得用.git文件夹判断更好吧，containerd不知道啥情况，额外增加一个无意义的.dockerenv文件不太合适吧。

**Comment by qingchoulove** [comment]
`.git`目录可能也是一样的问题，`.dockerenv`就是一个flag，可以保证在咱们打包的镜像中存在。或者换一个其他的环境变量，在`dockerfile`中指明，毕竟`dockerfile`对我们是可控的。

**Comment by ljtnono** [comment]
> `.git`目录可能也是一样的问题，`.dockerenv`就是一个flag，可以保证在咱们打包的镜像中存在。或者换一个其他的环境变量，在`dockerfile`中指明，毕竟`dockerfile`对我们是可控的。

那这有点像添加一个环境变量来判断运行环境了。

**Comment by ljtnono** [comment]
> `.git`目录可能也是一样的问题，`.dockerenv`就是一个flag，可以保证在咱们打包的镜像中存在。或者换一个其他的环境变量，在`dockerfile`中指明，毕竟`dockerfile`对我们是可控的。

嗯，也有道理
