### ISSUE TITLE
我想讨论下，如果把python版本升上去，当前的项目里会不会有坑？

### ISSUE THREAD

**Issue by Tarhyru** [opennaslab/kubespider#244]
我想尝试改善下二开体验，开发时支持代码热更新，结果发现当前指定的 python版本是3.1
而 watchdog 只支持，2.6，2.7 以及 3.4 以上的版本,原因似乎是 3.1 collections 模块中不存在的 MutableSet 属性。
我找了个 downloaders 的子项目，直接升到 3.8 去似乎没有问题

[demo](https://github.com/Tarhyru/kubespider/tree/feature/docker/downloaders/yt-dlp)

直接  docker-compose up 可以启动 /app 内的文件改变会热更新

**Comment by richardli1598** [comment]
我这边用的都是3.10，不是3.1

**Comment by miRemid** [comment]
测试3.8，3.9，3.10都没问题，顺便问下是哪个文档里面提及了3.1版本？

**Comment by richardli1598** [comment]
Hello, 感谢贡献！  之前你提过PR，这里邀请你成为org member, 点击这里确认：https://github.com/settings/organizations

**Comment by Tarhyru** [comment]
> 测试3.8，3.9，3.10都没问题，顺便问下是哪个文档里面提及了3.1版本？

可能是我描述不当...
这个项目里所有的docker里都有这么一行

https://github.com/opennaslab/kubespider/blob/795fa36b80ce368b3fb92e60f054f79a7edd59ee/Dockerfile#L3C1-L3C24

```
FROM python:3.10-alpine
```

也就是说，构筑出来的产物是在用 python 3.10 跑，总之我可以认为，升级这个是没有副作用的咯...

**Comment by Tarhyru** [comment]
原来如此，我就说往下找watchdog，没有一个跑的起来的...是我误解闹笑话了，

**Comment by ljtnono** [comment]
好像3.11版本会出现问题
