### ISSUE TITLE
交流沟通

### ISSUE THREAD

**Issue by evell1992** [opennaslab/kubespider#248]
我非常喜欢这个项目,目前有没有用户交流群,很想参与进来,啊啊啊啊啊啊

**Comment by richardli1598** [comment]
非常欢迎

**Comment by richardli1598** [comment]
> 为啥用电报啊

wechat有比较多的限制，看其他开源项目都用的电报

**Comment by evell1992** [comment]
> Telegram Invite link: https://t.me/+RR09tPuCvI9iNTc1

墙住了..

**Comment by evell1992** [comment]
> 非常欢迎
我看到后续计划里面推送
我之前看到一个开源项目是做消息推送的: [pushdeer](https://github.com/easychen/pushdeer)
希望有所帮助

**Comment by qingchoulove** [comment]
> > 非常欢迎
> > 我看到后续计划里面推送
> > 我之前看到一个开源项目是做消息推送的: [pushdeer](https://github.com/easychen/pushdeer)
> > 希望有所帮助

大佬是否有兴趣来添加下这个能力呢？

**Comment by evell1992** [comment]
> > > 非常欢迎
> > > 我看到后续计划里面推送
> > > 我之前看到一个开源项目是做消息推送的: [pushdeer](https://github.com/easychen/pushdeer)
> > > 希望有所帮助
> 
> 大佬是否有兴趣来添加下这个能力呢？

我不是大佬,但是我非常乐意参与到开发中来
我介绍下我的基本情况:
 - 我的时间比较零散,都是摸鱼抽出来的,很难有连续的长时间开发
 - 这个项目,我前几天刚发现,代码还没仔细看
 - 这个功能目前没有有规划,如果时间上没有问题的话这个需求我可以接~

**Comment by qingchoulove** [comment]
> > > > 非常欢迎
> > > > 我看到后续计划里面推送
> > > > 我之前看到一个开源项目是做消息推送的: [pushdeer](https://github.com/easychen/pushdeer)
> > > > 希望有所帮助
> > 
> > 
> > 大佬是否有兴趣来添加下这个能力呢？
> 
> 我不是大佬,但是我非常乐意参与到开发中来 我介绍下我的基本情况:
> 
> * 我的时间比较零散,都是摸鱼抽出来的,很难有连续的长时间开发
> * 这个项目,我前几天刚发现,代码还没仔细看
> * 这个功能目前没有有规划,如果时间上没有问题的话这个需求我可以接~

完全没有问题，让我们共同构建更好的下载体验。稍候我发一个issues来跟踪这个特性。非常期待大佬PR。
