### ISSUE TITLE
不支持Docker直接部署吗

### ISSUE THREAD

**Issue by wangsunlight** [opennaslab/kubespider#25]
不支持Docker直接部署吗？

**Comment by jwcesign** [comment]
支持的，这个一键安装脚本，本质上就是用docker run的
```sh
git clone https://github.com/jwcesign/kubespider.git
cd kubespider
bash hack/install.sh
```

**Comment by jwcesign** [comment]
By the way，感谢试用

**Comment by wangsunlight** [comment]
ok，thank

**Comment by jwcesign** [comment]
hello, @wangsunlight ，怎么样？用起来了吗？

**Comment by carrymaniac** [comment]
hi 我在mac上打算使用docker for mac直接部署aria2和kubespider 但是在配置aria2的时候遇到问题 插件没办法连接到docker里的aria2-pro 服务， 想问问这套服务不能在mac单机运行吗

**Comment by miRemid** [comment]
运行环境不受影响，如果可以话能否方便提供你的配置文件包括aria2和kubespider相关内容（务必处理敏感信息），这样我们也可以方便解决问题

**Comment by jwcesign** [comment]
1.你的是什么芯片的mac？ x86还是M1/m2?
2.插件连接到aria2-pro，你是指aria2的chrome插件？还是kubespider的插件？

**Comment by qingchoulove** [comment]
跨容器链接如果可以考虑通过
docker network create 创建一个命名网络，然后启动容器时通过--net 将两个容器加入相同网络。
或者通过host 网络连接两个服务。

**Comment by carrymaniac** [comment]
@qingchoulove 
好的 我对docker不太熟悉 晚些试一下看看 谢谢你的建议 感谢

**Comment by carrymaniac** [comment]
@miRemid hi 我并没有进行额外的配置 就是在一个x86的mac运行hack/install_kubespider.sh之后，docker显示aria2pro的容器正在运行，但是chrome插件没办法连上docker中的aria2

**Comment by miRemid** [comment]
请仔细检查你的chrome插件配置，例如连接的IP地址以及端口是否是RPC端口，例如`http://192.168.1.100:6800/jsonrpc`，另外请检查是否配置`Secret Key`选项为`kubespider`

以Aria2 Explorer插件为例：
![image](https://user-images.githubusercontent.com/35894052/235890111-1727d3ef-8a4b-49af-840e-37de04e1ce5c.png)
![image](https://user-images.githubusercontent.com/35894052/235890140-3eacd39c-6f43-477b-ae55-cb63a72882c6.png)

**Comment by carrymaniac** [comment]
@miRemid  hi 谢谢你的建议 我试了一下还是不行 不知道这是否和mac的docker的网络模式有关，目前我关闭了系统的代理和chrome的代理插件 仍然没办法连接。

**Comment by miRemid** [comment]
我没有mac电脑也无法复现问题，不过你可以尝试手动更改一下aria2的启动项，在`hach/install_kubespider.sh`中，将第32行开始的启动指令更改为下面这个试一试
```shell
# 5.Deploy aria2
docker run -d \
    --name aria2-pro \
    --restart unless-stopped \
    --log-opt max-size=1m \
    -p 6800:6800 \
	-p 6888:6888 \
    -e PUID=$UID \
    -e PGID=$GID \
    -e RPC_SECRET=kubespider \
    -e RPC_PORT=6800 \
    -e LISTEN_PORT=6888 \
    -v ${HOME}/kubespider/aria2/:/config \
    -v ${HOME}/kubespider/nas/:/downloads/ \
    ${image_registry}/aria2-pro:latest
```
随后，在插件中将127.0.0.1或localhost选择性的更改为Docker创建的网桥IP地址

如果这样还无法连接的话，我也不清楚该怎么改了（我没有mac）😂

**Comment by jwcesign** [comment]
我mac试了，也不行，没看懂mac的网络模式怎么处理的。。

**Comment by jwcesign** [comment]
cc @carrymaniac 换个机器吧，哈哈😄

**Comment by qingchoulove** [comment]
@carrymaniac hello，能确认下mac使用的docker软件么？我在mac环境使用rancher desktop进行部署。

```
nerdctl run -d \
    --name aria2-pro \
    --log-opt max-size=1m \
    --network host \
    -e RPC_SECRET=kubespider \
    -e RPC_PORT=6800 \
    -e LISTEN_PORT=6888 \
    -v ${HOME}/kubespider/aria2/:/config \
    -v ${HOME}/kubespider/nas/:/downloads/ \
    -p 6800:6800 cesign/aria2-pro
    
```

```
CONTAINER ID    IMAGE                                COMMAND    CREATED          STATUS    PORTS    NAMES
4cee0570fa47    docker.io/cesign/aria2-pro:latest    "/init"    5 minutes ago    Up                 aria2-pro
```
参照下图是可以正常使用chrome插件链接的。
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/9648420/236688317-99b21af6-ddb9-4ebe-82c7-2ff0be1b577c.png">
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/9648420/236688323-fcf7690e-7edc-454e-8453-f6d1422659be.png">

**Comment by carrymaniac** [comment]
@qingchoulove 很抱歉我回复晚了 这是我使用的docker desktop的版本信息
<img width="757" alt="image" src="https://github.com/jwcesign/kubespider/assets/30337438/95e67eb6-5d77-42af-af1c-8243cdbd8651">

**Comment by ljtnono** [comment]
@jwcesign 
mac上的docker desktop是不支持docker run --network host 选项的，所以会导致默认的安装脚本里面安装的127.0.0.1在容器中被认为是容器自己的循环地址。所以在mac上安装时需要改一下安装脚本(hack/install_kubespider.sh)：

```bash

#!/bin/sh

set -e

# 1.Load env and echo logo
source hack/env.sh

echo "[INFO] Start to deploy with default configuration..."

# 2.Check env
ret=`docker version`
if [[ $? != 0 ]]; then
    echo "[ERROR] Please install docker"
    exit 1
fi

# 3.Create necessary directory
mkdir -p ${KUBESPIDER_HOME}/kubespider/nas/
mkdir -p ${KUBESPIDER_HOME}/kubespider/aria2/

# 4.Set registry
source hack/util.sh
util::set_registry_for_image

# 5.Deploy aria2
docker run -d \
    --name aria2-pro \
    --restart unless-stopped \
    --log-opt max-size=1m \
    # 去掉这一行，并手动映射端口
    ## --network host \
    -p 6800:6800 \
    -p 6888:6888 \
    -e PUID=$UID \
    -e PGID=$GID \
    -e RPC_SECRET=kubespider \
    -e RPC_PORT=6800 \
    -e LISTEN_PORT=6888 \
    -v ${KUBESPIDER_HOME}/kubespider/aria2/:/config \
    -v ${KUBESPIDER_HOME}/kubespider/nas/:/downloads/ \
    ${image_registry}/aria2-pro:latest

# 6.Deploy kubespider
export KUBESPIDER_DEFAULT_VERSION="latest"
if [[ ${KUBESPIDER_VERSION} == "" ]]; then
    export KUBESPIDER_VERSION=${KUBESPIDER_DEFAULT_VERSION}
fi
docker run -itd --name kubespider \
    -v ${KUBESPIDER_HOME}/kubespider/.config:/app/.config \
    -e PUID=$UID \
    -e PGID=$GID \
    # 去掉这一行，并手动映射端口
    ## --network=host \
    -p 3080:3080 \
    --restart unless-stopped \
    ${image_registry}/kubespider:${KUBESPIDER_VERSION}

# 7.Give necessary info
echo "[INFO] Deploy successful, check the information:"
echo "*******************************************"
echo "Kubespider config path: ${KUBESPIDER_HOME}/kubespider/.config"
echo "Download file path: ${KUBESPIDER_HOME}/kubespider/nas/"
echo "Kubespider webhook address: http://<server_ip>:3080"
echo "Aria2 server address: http://<server_ip>:6800/jsonrpc, you can use any gui or webui to connect it"
echo "Aria2 default secret is:kubespider"
echo "*******************************************"

```

等容器跑起来之后，再进入aria2容器中使用ip addr 命令查看docker分配的ip地址，然后将这个ip地址修改到配置文件中，然后重启容器就好了，chrome插件的server地址也需要用这个ip地址

**Comment by miRemid** [comment]
> @jwcesign 
> mac上的docker desktop是不支持docker run --network host 选项的，所以会导致默认的安装脚本里面安装的127.0.0.1在容器中被认为是容器自己的循环地址。所以在mac上安装时需要改一下安装脚本(hack/install_kubespider.sh)：
> 
> ```bash
> 
> #!/bin/sh
> 
> set -e
> 
> # 1.Load env and echo logo
> source hack/env.sh
> 
> echo "[INFO] Start to deploy with default configuration..."
> 
> # 2.Check env
> ret=`docker version`
> if [[ $? != 0 ]]; then
>     echo "[ERROR] Please install docker"
>     exit 1
> fi
> 
> # 3.Create necessary directory
> mkdir -p ${KUBESPIDER_HOME}/kubespider/nas/
> mkdir -p ${KUBESPIDER_HOME}/kubespider/aria2/
> 
> # 4.Set registry
> source hack/util.sh
> util::set_registry_for_image
> 
> # 5.Deploy aria2
> docker run -d \
>     --name aria2-pro \
>     --restart unless-stopped \
>     --log-opt max-size=1m \
>     # 去掉这一行，并手动映射端口
>     ## --network host \
>     -p 6800:6800 \
>     -p 6888:6888 \
>     -e PUID=$UID \
>     -e PGID=$GID \
>     -e RPC_SECRET=kubespider \
>     -e RPC_PORT=6800 \
>     -e LISTEN_PORT=6888 \
>     -v ${KUBESPIDER_HOME}/kubespider/aria2/:/config \
>     -v ${KUBESPIDER_HOME}/kubespider/nas/:/downloads/ \
>     ${image_registry}/aria2-pro:latest
> 
> # 6.Deploy kubespider
> export KUBESPIDER_DEFAULT_VERSION="latest"
> if [[ ${KUBESPIDER_VERSION} == "" ]]; then
>     export KUBESPIDER_VERSION=${KUBESPIDER_DEFAULT_VERSION}
> fi
> docker run -itd --name kubespider \
>     -v ${KUBESPIDER_HOME}/kubespider/.config:/app/.config \
>     -e PUID=$UID \
>     -e PGID=$GID \
>     # 去掉这一行，并手动映射端口
>     ## --network=host \
>     -p 3080:3080 \
>     --restart unless-stopped \
>     ${image_registry}/kubespider:${KUBESPIDER_VERSION}
> 
> # 7.Give necessary info
> echo "[INFO] Deploy successful, check the information:"
> echo "*******************************************"
> echo "Kubespider config path: ${KUBESPIDER_HOME}/kubespider/.config"
> echo "Download file path: ${KUBESPIDER_HOME}/kubespider/nas/"
> echo "Kubespider webhook address: http://<server_ip>:3080"
> echo "Aria2 server address: http://<server_ip>:6800/jsonrpc, you can use any gui or webui to connect it"
> echo "Aria2 default secret is:kubespider"
> echo "*******************************************"
> 
> ```
> 
> 等容器跑起来之后，再进入aria2容器中使用ip addr 命令查看docker分配的ip地址，然后将这个ip地址修改到配置文件中，然后重启容器就好了，chrome插件的server地址也需要用这个ip地址

大佬可以提个pr来适配一下macos吗？
