### ISSUE TITLE
feat: add notifications

### ISSUE THREAD

**Issue by qingchoulove** [opennaslab/kubespider#257]
## Describe the background
Send a notification to the user when a task is successfully added, or when a download is accepted from rss

## Describe the feature
- Easy to extend more notification platforms
- It is possible to configure for each provider
- Stable and easy-to-use api
- More features from the community

**Comment by qingchoulove** [comment]
@evell1992

**Comment by evell1992** [comment]
> 

ok

**Comment by evell1992** [comment]
这个功能基本已经完成了,剩下的应该就是优化,补文档和测试了.开发的过程中我一直想沟通一些想法,但是telegram一直注册不上.买的session,mac也不知道怎么用,接码平台也接不到码..有没有什么攻略啊,我学习学习@qingchoulove

**Comment by qingchoulove** [comment]
> 这个功能基本已经完成了,剩下的应该就是优化,补文档和测试了.开发的过程中我一直想沟通一些想法,但是telegram一直注册不上.买的session,mac也不知道怎么用,接码平台也接不到码..有没有什么攻略啊,我学习学习@qingchoulove

可以邮件我你的其他IM么，我们一起看下？(me@kyun.me)

**Comment by richardli1598** [comment]
hello @evell1992 , 我之前还想到一个问题，支持类似：我把链接发 wechat 或者其他，然后相关机器人接受到这个消息，发送kubespider触发下载


这个感觉还挺有用的，你可以一起看看

**Comment by evell1992** [comment]
这个问题我也想过,要实现这个功能,不管kubespider主动去获取要下载的链接,还是被动接受下载链接都需要一个中间服务器
我了解实现方案有两种:
第一种是利用企业微信或者钉钉之类的商业软件(微信可能不太可行)的机器人功能来发送和接受下载链接
第二种是自己有公网ip在公网上架设服务
我不太喜欢第一种方案,原因可以参考[pushdeer]这个项目,pushdeer在立项之前就是用的微信公众号来推送消息的,后来公众号的限制越来越多,
在尝试了很多种方案之后(可能也包括企业微信消息推送,时间太久了,我记不清了)都放弃了,最终下定决心开发的pushdeer.
所以如果要用商业软件的这些免费功能,可能出现的限制有很多,并且不可控,比如政策调整,消息内容审核等等潜在风险
第二种方案的话需要有一个免费的服务器来提供下载消息的收发,不然没有公网的用户就用不了这个功能.pushdeer在尝试了很多方案之后,最后采用的是
接受服务器赞助,给赞助商打广告的方式获取的服务器资源免费提供给用户使用的.
综上所述,第一种方案我不太愿意做,原因是说不准哪天就没用了,第二种方案的话我个人觉得对于kubespider而言为时过早.
或者有其他实现方式也可以聊聊,方案成熟的话可以一试.@richardli1598

**Comment by evell1992** [comment]
还有一个,迅雷的nas版在内测中,迅雷手机客户端可以远程控制nas版本的迅雷进行下载
方式和你讲的差不多,就是把一个链接推送到nas的迅雷上远程控制下载,不清楚这个你是否了解@richardli1598

**Comment by richardli1598** [comment]
我更喜欢第一种，可以支持特定平台（不对接敏感平台），比如比较开放的Telegram。我更喜欢的原因主要是，好用&方便。
第二种服务器会接收用户数据，比较敏感。
@qingchoulove @evell1992 你们觉得呢？

**Comment by evell1992** [comment]
> 我更喜欢第一种，可以支持特定平台（不对接敏感平台），比如比较开放的Telegram。我更喜欢的原因主要是，好用&方便。 第二种服务器会接收用户数据，比较敏感。 @qingchoulove @evell1992 你们觉得呢？

我不喜欢第一种方案的原因就是没有找到一个可以信任的三方平台来接入,如果有的话肯定是比第二个方案来的简单好用.Telegram 我注册不上,目前都没有办法体验..
