### ISSUE TITLE
报错是什么原因 docker: Error response from daemon: Bind mount failed: '/volume2/kubespider/.config' does not exists.

### ISSUE THREAD

**Issue by bruseyun** [opennaslab/kubespider#266]
## Ask your question here:
官方群晖流程报错如下

docker: Error response from daemon: Bind mount failed: '/volume2/kubespider/.config' does not exists.

环境：群晖 920
流程：参考官方的群晖部署流程，进入 bash install 环节就一直报这个错误，容器倒是都安装好了，可是报错后就没法看到 aria2 的链接密钥。
尝试：
- chmod 777 给了 kubespider 共享文件夹和 bash 文件，不行
- kubespider 的共享文件夹赋予 everyone 权限，也还是不行

**Comment by richardli1598** [comment]
用群晖的file station把文件夹 .config创建一下？

**Comment by bruseyun** [comment]
手动创建后 ok 了，谢谢

虽然还是不理解为什么脚本没有权限创建这个文件夹

**Comment by richardli1598** [comment]
可以麻烦把文档修改一下吗？https://github.com/opennaslab/kubespider/blob/main/docs/zh/user_guide/synology_installation/README.md  把创建.config的步骤进去

**Comment by richardli1598** [comment]
应该是这个添加一行：https://github.com/opennaslab/kubespider/blob/ca27e16a30b00b99f738c360c30bc1a85e97a490/hack/install_kubespider.sh#L19

```sh
mkdir -p ${KUBESPIDER_HOME}/kubespider/.config
```

可以麻烦提个PR修改一下吗？

**Comment by richardli1598** [comment]
文档不用改，直接这个修改一下这个就行了：![image](https://github.com/opennaslab/kubespider/assets/135685576/502c2c9f-abb0-48e3-81db-f782ecd31e2d) 
你修改后我提个PR，你在你库上修改一下就行： https://github.com/bruseyun/kubespider/edit/main/hack/install_kubespider.sh

**Comment by bruseyun** [comment]
已提交

**Comment by richardli1598** [comment]
Thanks!
