### ISSUE TITLE
迅雷没有对应的版本，应该怎么修改啊

### ISSUE THREAD

**Issue by yeyudoc** [opennaslab/kubespider#278]
## Ask your question here:
![image](https://github.com/opennaslab/kubespider/assets/83936435/fb3ae7d6-f521-4dde-b12f-20c920ecb69e)
可以单独下载其他的迅雷吗，应该怎么修改

**Comment by yeyudoc** [comment]
拉取后无法启动，
需要arm64版本

**Comment by qingchoulove** [comment]
现在没有打包arm64版本，我确认下上游是否支持，如果可以支持的话，会在近期增加arm64镜像构建。

**Comment by qingchoulove** [comment]
@yeyudoc 新增arm64镜像，大佬可以尝试下，有问题请re-open.
