### ISSUE TITLE
迅雷下载用不了了

### ISSUE THREAD

**Issue by Hotwill** [opennaslab/kubespider#294]
## Describe the bug
前几天迅雷下载正常，今天突然不能用了。
日志报错：
ERROR: Get xunlei token error:Expecting value: line 1 column 1 (char 0)
看了下代码，发现是这里没有返回：
https://github.com/opennaslab/kubespider/blob/fa5b3b212c177d8cb9946c8f28a7c2f804a72878/kubespider/download_provider/xunlei_download_provider/provider.py#L199C14-L199C14

## Describe the running environment
运行环境：docker
版本：[v0.3.0](https://hub.docker.com/layers/cesign/kubespider/v0.3.0/images/sha256-85fb6ed879e86527f131080c53bb4b97bd5793dd8589a279fe96edf8b490203a?context=explore)

**Comment by richardli1598** [comment]
你指示的这行：看起来是迅雷没访问通？
```
rep = self.request_handler.get(self.http_endpoint + '/webman/3rdparty/pan-xunlei-com/index.cgi/device/now',
                                           timeout=30)
```
可以curl一下迅雷的这个接口，看看是否ok吗？

**Comment by richardli1598** [comment]
问题已修复，请更新镜像即可。

**Comment by Hotwill** [comment]
> 你指示的这行：看起来是迅雷没访问通？
> 
> ```
> rep = self.request_handler.get(self.http_endpoint + '/webman/3rdparty/pan-xunlei-com/index.cgi/device/now',
>                                            timeout=30)
> ```
> 
> 可以curl一下迅雷的这个接口，看看是否ok吗？

![image](https://github.com/opennaslab/kubespider/assets/7548705/63b0f6e8-c067-491b-9c3d-8964ca870bc0)
本地curl返回401
现在连配置里的第一步也返回401了：
`curl http://<server_ip>:2345/webman/3rdparty/pan-xunlei-com/index.cgi/\#/home`
前几天一切正常

**Comment by richardli1598** [comment]
是不是你迅雷没登陆？

**Comment by Hotwill** [comment]
登陆了，迅雷网页端下载正常。
那奇怪了，难道只有我这里有问题？！

**Comment by richardli1598** [comment]
更新一下Kubespider镜像试试？

**Comment by Hotwill** [comment]
搞明白原因了，是我的问题，忘记什么时候给迅雷添加了密码认证了。
![image](https://github.com/opennaslab/kubespider/assets/7548705/736ae6d7-914b-4d58-bc55-2034fb31e56a)

**Comment by richardli1598** [comment]
@Hotwill 可以在项目FAQ里面加一下文档描述一下这个问题吗？感谢

**Comment by Hotwill** [comment]
> @Hotwill 可以在项目FAQ里面加一下文档描述一下这个问题吗？感谢

@richardli1598 在迅雷配置文档里说明了，看是否可行？https://github.com/opennaslab/kubespider/pull/296/commits/0221e2178c5598a732c2e4ddb3b4fa38b4e83f76
