### ISSUE TITLE
通过浏览器插件向kubespider发送btbtt12的下载链接，不能正常下载

### ISSUE THREAD

**Issue by LeanFly** [opennaslab/kubespider#336]
## Describe the bug
通过浏览器插件向kubespider发送btbtt12的下载链接，下载器没有添加下载任务，尝试切换 tr和qbit都不能添加下载任务，通过_docker logs -f_ 命令查看到的日志如下：
![image](https://github.com/opennaslab/kubespider/assets/18253047/3dca2a3a-a867-4ae2-9f8a-d2666e7ddfa9)

2023-09-07 22:51:39,257-INFO: File handler start running...
2023-09-07 22:51:39,309-INFO: Source Provider:btbtt12_disposable_source_provider enabled...
2023-09-07 22:51:39,313-INFO: Source Provider:meijutt_source_provider enabled...
2023-09-07 22:51:39,316-INFO: Source Provider:bilibili_source_provider enabled...
2023-09-07 22:51:39,320-INFO: Source Provider:youtube_source_provider enabled...
2023-09-07 22:51:39,355-INFO: Download Provider:transmission enabled...
2023-09-07 22:51:39,363-INFO: Period Server Queue handler start running...
2023-09-07 22:51:39,363-INFO: Download trigger job start running...
2023-09-07 22:51:39,363-INFO: PT Server start running...
2023-09-07 22:51:39,363-INFO: Notification Server Queue handler start running...
2023-09-07 22:51:39,363-INFO: Period Server producer start running...
2023-09-07 22:51:39,364-INFO: Webhook Server start running...
2023-09-07 22:51:39,365-INFO: Serving on http://0.0.0.0:3080
2023-09-07 22:51:40,368-INFO: meijutt tv link is:
2023-09-07 23:51:39,449-INFO: meijutt tv link is:
2023-09-08 00:51:39,549-INFO: meijutt tv link is:
2023-09-08 01:51:39,619-INFO: meijutt tv link is:
2023-09-08 02:51:39,716-INFO: meijutt tv link is:
2023-09-08 03:51:39,817-INFO: meijutt tv link is:
2023-09-08 04:51:39,902-INFO: meijutt tv link is:
2023-09-08 05:51:39,999-INFO: meijutt tv link is:
2023-09-08 06:51:40,098-INFO: meijutt tv link is:
2023-09-08 07:51:40,189-INFO: meijutt tv link is:
2023-09-08 08:47:44,919-INFO: Get webhook trigger:https://www.btbtt12.com/attach-dialog-fid-951-aid-6101498.htm
2023-09-08 08:47:44,919-INFO: https://www.btbtt12.com/attach-dialog-fid-951-aid-6101498.htm belongs to Btbtt12DisposableSourceProvider
2023-09-08 08:47:44,920-INFO: btbtt12_disposable_source_provider parse https://www.btbtt12.com/attach-dialog-fid-951-aid-6101498.htm as https://www.btbtt12.com/attach-download-fid-951-aid-6101498.htm
2023-09-08 08:47:45,822-INFO: filter downloader type:None, names:None
2023-09-08 08:47:45,822-INFO: download link type None, with provider size 1
2023-09-08 08:47:45,822-WARNING: Unknown link type:None
2023-09-08 08:51:40,289-INFO: meijutt tv link is:

## Describe the running environment

群晖 6.24
通过 docker cli 方式安装
拉取的是最新的镜像

**Comment by miRemid** [comment]
感谢使用kubespider！能否提供一下你的download_provider的配置文件呢？另外使用的kubespider是什么版本？

我这里使用latest镜像，启动qbittorrent后，在[btbtt12.com/attach-dialog-fid-951-aid-6101498.htm](https://www.btbtt12.com/attach-dialog-fid-951-aid-6101498.htm)中发送下载链接是可以正常下载的

**Comment by evell1992** [comment]
改下这个文件kubespider/kubespider/source_provider/btbtt12_disposable_source_provider/provider.py
74行:
        return [Resource(
            url=ret,
            path=title,
            file_type=file_type,
            link_type=self.get_link_type(),
        )]
加一个 link_type 试试看

**Comment by LeanFly** [comment]
> 改下这个文件kubespider/kubespider/source_provider/btbtt12_disposable_source_provider/provider.py 74行: return [Resource( url=ret, path=title, file_type=file_type, link_type=self.get_link_type(), )] 加一个 link_type 试试看

改动之后下载正常了。非常感谢~

**Comment by LeanFly** [comment]
> 感谢使用kubespider！能否提供一下你的download_provider的配置文件呢？
> 
> 我这里复现同样使用latest镜像，并开启qbittorrent，在[btbtt12.com/attach-dialog-fid-951-aid-6101498.htm](https://www.btbtt12.com/attach-dialog-fid-951-aid-6101498.htm)中发送下载链接是可以正常下载的
> 
> ```shell
> 2023-09-08 09:39:30,734-INFO: Source Provider:btbtt12_disposable_source_provider enabled...
> 2023-09-08 09:39:30,737-INFO: Source Provider:meijutt_source_provider enabled...
> 2023-09-08 09:39:30,741-INFO: Source Provider:bilibili_source_provider enabled...
> 2023-09-08 09:39:30,744-INFO: Source Provider:youtube_source_provider enabled...
> 2023-09-08 09:39:30,765-INFO: Download Provider:aria2 enabled...
> 2023-09-08 09:39:30,768-INFO: Download Provider:qbittorrent enabled...
> 2023-09-08 09:39:30,783-INFO: Period Server producer start running...
> 2023-09-08 09:39:30,783-INFO: Download trigger job start running...
> 2023-09-08 09:39:30,783-INFO: PT Server start running...
> 2023-09-08 09:39:30,784-INFO: Period Server Queue handler start running...
> 2023-09-08 09:39:30,784-INFO: Notification Server Queue handler start running...
> 2023-09-08 09:39:30,784-INFO: Webhook Server start running...
> 2023-09-08 09:39:30,785-INFO: Serving on http://0.0.0.0:3080
> 2023-09-08 09:39:31,789-INFO: meijutt tv link is:
> 2023-09-08 09:39:33,740-INFO: Source Provider:btbtt12_disposable_source_provider enabled...
> 2023-09-08 09:39:33,744-INFO: Source Provider:meijutt_source_provider enabled...
> 2023-09-08 09:39:33,747-INFO: Source Provider:bilibili_source_provider enabled...
> 2023-09-08 09:39:33,750-INFO: Source Provider:youtube_source_provider enabled...
> 2023-09-08 09:39:33,771-INFO: Download Provider:aria2 enabled...
> 2023-09-08 09:39:33,774-INFO: Download Provider:qbittorrent enabled...
> 2023-09-08 09:39:33,789-INFO: Period Server Queue handler start running...
> 2023-09-08 09:39:33,790-INFO: Webhook Server start running...
> 2023-09-08 09:39:33,790-INFO: Notification Server Queue handler start running...
> 2023-09-08 09:39:33,790-INFO: Download trigger job start running...
> 2023-09-08 09:39:33,791-INFO: Period Server producer start running...
> 2023-09-08 09:39:33,791-INFO: PT Server start running...
> 2023-09-08 09:39:33,791-INFO: Serving on http://0.0.0.0:3080
> 2023-09-08 09:39:34,794-INFO: meijutt tv link is:
> 2023-09-08 09:40:20,986-INFO: Get webhook trigger:https://www.btbtt12.com/attach-download-fid-951-aid-6101498.htm
> 2023-09-08 09:40:27,102-INFO: download link type torrent, with provider size 2
> 2023-09-08 09:40:28,191-INFO: Download torrent file with downloader(aria2)
> 2023-09-08 09:40:28,203-INFO: Start torrent download:/tmp/7f33e63d23649ad488fe1d854a6a903d.torrent
> 2023-09-08 09:40:28,208-WARNING: Please ensure your aria2 server is ok:HTTPConnectionPool(host='127.0.0.1', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f9a01bbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 2023-09-08 09:40:28,208-WARNING: Download torrent file error:HTTPConnectionPool(host='127.0.0.1', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f9a01bbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 2023-09-08 09:40:28,208-INFO: Download torrent file with downloader(qbittorrent)
> 2023-09-08 09:40:28,352-INFO: Start torrent download:/tmp/7f33e63d23649ad488fe1d854a6a903d.torrent, path:/downloads/Common/
> 2023-09-08 09:40:28,352-INFO: Create download task category:None, tags:['kubespider']
> 2023-09-08 09:40:28,361-INFO: Create download task results:Ok.
> ```

> 
---
yt-dlp:
  type: ytdlp_download_provider
  enable: false
  http_endpoint_host: http://127.0.0.1
  http_endpoint_port: 3082
  auto_format_convet: false
  target_format: mp4
  download_proxy: http://192.168.1.8:1087
  priority: 0
youget:
  type: youget_download_provider
  enable: false
  http_endpoint_host: http://127.0.0.1
  http_endpoint_port: 3081
  priority: 1
aria2:
  type: aria2_download_provider
  enable: false
  download_base_path: "/downloads/"
  rpc_endpoint_host: http://127.0.0.1
  rpc_endpoint_port: 6800
  secret: kubespider
  priority: 2
qbittorrent:
  type: qbittorrent_download_provider
  enable: true
  download_base_path: "/mv/"
  http_endpoint_host: http://172.17.0.1
  http_endpoint_port: port
  username: user
  password: pass
  verify_webui_certificate: false
  priority: 0
  tags:
    - kubespider
xunlei:
  type: xunlei_download_provider
  enable: false
  token_js_path: "/app/.config/dependencies/xunlei_download_provider/get_token.js"
  http_endpoint: http://127.0.0.1:2345
  device_id: 5c78ea560a34ed4b4fbe6686da1172b4
  priority: 4
transmission:
  type: transmission_download_provider
  enable: true
  download_base_path: "/mv"
  http_endpoint: http://ip:port/transmission/rpc
  username: user
  password: pass
  priority: 1
tiktok-dlp:
  type: tiktok_download_provider
  enable: false
  priority: 6
  http_endpoint_host: http://127.0.0.1
  http_endpoint_port: 3083
  cookie:

**Comment by richardli1598** [comment]
@LeanFly 能提个PR修复一下这个问题吗？

**Comment by LeanFly** [comment]
> @LeanFly 能提个PR修复一下这个问题吗？

嗯嗯，已经提交了
