### ISSUE TITLE
请问公网访问kubespider服务配置事

### ISSUE THREAD

**Issue by iamverydm** [opennaslab/kubespider#366]
大佬好，目前我在群晖中已经部署好了kubespider并且能够正常使用，服务器地址为nas本地地址加3080端口，我的nas使用了公网域名解析，在公网使用域名访问DSM都是正常联通的，于是我使用反向代理将kubespider服务器地址和端口代理到了公网域名+3090端口，在公网端却无法连接kubespider服务器，插件显示save error，看手册也没看到公网访问相关tag，请问公网访问还需要配置其他地方吗？感谢。

**Comment by iamverydm** [comment]
已经解决了，不能用https，反代也是要反代http，供大家参考

**Comment by mrhello369** [comment]
感谢使用, 可以在这里加一个FAQ吗？ https://github.com/opennaslab/kubespider/blob/main/docs/en/faq.md
