### ISSUE TITLE
docker运行后，浏览器访问404页面

### ISSUE THREAD

**Issue by squkw** [opennaslab/kubespider#444]
docker run -itd --name kubespider  -v ~/kubespider:/app/.config -p 3080:3080 cesign/kubespider:latest

浏览器访问http://localhost:3080/ 响应404
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

docker的确是启动成功了，如果stop，浏览器访问，没响应

**Comment by qingchoulove** [comment]
非常感谢提交反馈。
请访问`http://localhost:3080/healthz`看下呢，我们api没有暴露'/' 这个path。

**Comment by squkw** [comment]
> 非常感谢提交反馈。 请访问`http://localhost:3080/healthz`看下呢，我们api没有暴露'/' 这个path。
`
http://localhost:3080/healthz
`
"OK"
意思是，这个项目是没有UI，纯接口的吗

**Comment by qingchoulove** [comment]
> > 非常感谢提交反馈。 请访问`http://localhost:3080/healthz`看下呢，我们api没有暴露'/' 这个path。
> > `http://localhost:3080/healthz`
> > "OK"
> > 意思是，这个项目是没有UI，纯接口的吗

是的 UI 还在初期的设计阶段。

**Comment by qingchoulove** [comment]
PC用户使用可以考虑使用我们提供的浏览器扩展 [chrome-extension](https://github.com/opennaslab/kubespider?tab=readme-ov-file#3install-chrome-plugin)
