### ISSUE TITLE
chrome插件能否支持发送剪切板中的磁链

### ISSUE THREAD

**Issue by rdcentermrzhi** [opennaslab/kubespider#475]

**Comment by qingchoulove** [comment]
Hello，能更详细描述下你的需求么？为什么还需要发送剪切板中的磁链，插件是支持直接把网页内容发送到Kubespider的呀。

**Comment by rdcentermrzhi** [comment]
> Hello，能更详细描述下你的需求么？为什么还需要发送剪切板中的磁链，插件是支持直接把网页内容发送到Kubespider的呀。

这个插件不能将网页中的文本内容直接发送吧、比如磁力链接直接显示在网页中只提供了一个copy选项 没有做超链接 就没法发送

**Comment by qingchoulove** [comment]
> > Hello，能更详细描述下你的需求么？为什么还需要发送剪切板中的磁链，插件是支持直接把网页内容发送到Kubespider的呀。
> 
> 这个插件不能将网页中的文本内容直接发送吧、比如磁力链接直接显示在网页中只提供了一个copy选项 没有做超链接 就没法发送

好的，我大致明白啦，我们近期会调研一下插件捕获内容的处理方式。非常感谢你的建议

**Comment by rdcentermrzhi** [comment]
> > > Hello，能更详细描述下你的需求么？为什么还需要发送剪切板中的磁链，插件是支持直接把网页内容发送到Kubespider的呀。
> > 
> > 
> > 这个插件不能将网页中的文本内容直接发送吧、比如磁力链接直接显示在网页中只提供了一个copy选项 没有做超链接 就没法发送
> 
> 好的，我大致明白啦，我们近期会调研一下插件捕获内容的处理方式。非常感谢你的建议

本来想自己搞一下，但是nodejs 确实不懂， 环境搞了一上午没弄起来，npm run dev 在windows 上会提示一个
![image](https://github.com/opennaslab/kubespider/assets/25632337/a13b57f3-6854-41d6-b9fd-8f7827899b95)
这个路径就很奇怪， 不知道是哪里环境配置的问题， 有时间可以考虑支持一下， 多谢

**Comment by qingchoulove** [comment]
@rdcentermrzhi 我们为插件添加了选中文本的支持，现在会首先发送选中文本到服务端。可以重装插件看下能否满足诉求。
