### ISSUE TITLE
会支持FireFox么？

### ISSUE THREAD

**Issue by manduted** [opennaslab/kubespider#501]
之前一直用Chrome，现在觉得FF好用，

插件应该是没有问题，兼容性我也拉去FF的兼容测试看了，
顶多也就是Service Worker无效，FF的manifest.json  background那有点区别。问题不大，插件拉进去也能正常读取
![1](https://github.com/opennaslab/kubespider/assets/47053686/1c1176be-b155-4bdc-8ea1-253c29540ea5)

![2](https://github.com/opennaslab/kubespider/assets/47053686/b2e85d6f-c3de-4ce6-961e-6f3061f0df48)

![3](https://github.com/opennaslab/kubespider/assets/47053686/10767836-df54-460c-963e-65cc4b0df2bd)

FF这玩意，会在请求头加个 图三那个，也就是Content-Security-Policy里面的upgrade-insecure-requests。。。U=1，然后就请求地址就变成了 https ..= =。。。顺带试了下反代，尝试改响应U=0，让浏览器不自动up，也没啥用。反而还提示CORS头缺少 'Access-Control-Allow-Origin'。（反代是有加，Access-Control-Allow-Origin: *，method也加了GET ,PUT）

然后google一圈，也没看见有怎么关。。都是让添加。这就很尴尬。Chrome是正常，只是研究下

**Comment by gygy** [comment]
> Hello @manduted 目前没有支持计划耶，可以试试这个，看能否转化： https://zhuanlan.zhihu.com/p/163535578

我按照以上方法进行操作，提示如下错误。应该是兼容性问题，但不知道如何修改
![image](https://github.com/opennaslab/kubespider/assets/2096830/fc787a3e-d06a-4bfe-b6f4-4afe4da994ee)

**Comment by qingchoulove** [comment]
@manduted @gygy #519 调整了扩展使用api的用法，现在应该已经可以正常在firefox使用，两位有兴趣可以帮忙验证下么？

**Comment by gygy** [comment]
> @manduted @gygy #519 调整了扩展使用api的用法，现在应该已经可以正常在firefox使用，两位有兴趣可以帮忙验证下么？

怎么下载？

**Comment by manduted** [comment]
> @manduted @gygy #519 调整了扩展使用api的用法，现在应该已经可以正常在firefox使用，两位有兴趣可以帮忙验证下么？

好。刚好也出差回来

**Comment by manduted** [comment]
> @manduted @gygy #519 调整了扩展使用api的用法，现在应该已经可以正常在firefox使用，两位有兴趣可以帮忙验证下么？

今天构建了一下。build和装载进去都是正常

![ScreenShot_2024-05-30_17-05-26](https://github.com/opennaslab/kubespider/assets/47053686/4c9dde6e-aa05-4591-96a9-cca137c7b7aa)
![ScreenShot_2024-05-30_17-07-52](https://github.com/opennaslab/kubespider/assets/47053686/4e0a3825-f327-49c6-a8b7-c84b2b59b018)


但还是这个问题：

![ScreenShot_2024-05-30_17-05-54](https://github.com/opennaslab/kubespider/assets/47053686/b0eb8957-e2ef-4525-b449-5aa41ce675de)

**Comment by manduted** [comment]
> > @manduted @gygy #519 调整了扩展使用api的用法，现在应该已经可以正常在firefox使用，两位有兴趣可以帮忙验证下么？
> 
> 今天构建了一下。build和装载进去都是正常
> 
> ![ScreenShot_2024-05-30_17-05-26](https://private-user-images.githubusercontent.com/47053686/335117022-4c9dde6e-aa05-4591-96a9-cca137c7b7aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjA0NDUsIm5iZiI6MTcxNzA2MDE0NSwicGF0aCI6Ii80NzA1MzY4Ni8zMzUxMTcwMjItNGM5ZGRlNmUtYWEwNS00NTkxLTk2YTktY2NhMTM3YzdiN2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA5MDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MTFlMmM2NWE0MmI4M2Q3YmFlMTY3Yjc3YjJiNWUwMmUxYzI1MmNhYTkwNzI1YmMyZDRkMDU1MjU2YjY3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Gdo7aV-xxGj5tlMQIDjJC_UrLy_ausTJMJH7Nw8Jxs) ![ScreenShot_2024-05-30_17-07-52](https://private-user-images.githubusercontent.com/47053686/335117538-4e0a3825-f327-49c6-a8b7-c84b2b59b018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjA0NDUsIm5iZiI6MTcxNzA2MDE0NSwicGF0aCI6Ii80NzA1MzY4Ni8zMzUxMTc1MzgtNGUwYTM4MjUtZjMyNy00OWM2LWE4YjctYzg0YjJiNTliMDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA5MDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjNlMzU5YzJjYmYzYjE0Njg3NzNlZjFjZDYxM2M2OGU2YmY2OWQ0MmU0ZmE5MjJhMjMyNDA0NTJmMTY4MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M0G5AzyyqB2YrH9FNJkivtqCnUuOfPF9sjalddL8Vp4)
> 
> 但还是这个问题：
> 
> ![ScreenShot_2024-05-30_17-05-54](https://private-user-images.githubusercontent.com/47053686/335117217-b0eb8957-e2ef-4525-b449-5aa41ce675de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjA0NDUsIm5iZiI6MTcxNzA2MDE0NSwicGF0aCI6Ii80NzA1MzY4Ni8zMzUxMTcyMTctYjBlYjg5NTctZTJlZi00NTI1LWI0NDktNWFhNDFjZTY3NWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA5MDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMTIyMWFjYmE1ODI5YWEwZTY2YmQxZGQ5OTg3ODUzOTA1NTAyYTZmZmEzMjVkYmEyNDI5NWY3MzFiNzY3NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.moUfB1npBfdqc7Ar0tle7T7fpFXZdNFQUegEA7j6MH0)

.........我忘了更新服务端。。。

**Comment by manduted** [comment]
> 怎么下载Firefox插件

要更新服务端。Core里面Api有更新。插件可以去我repositories 里面。我构建了插件。

**Comment by manduted** [comment]
> @manduted @gygy #519 调整了扩展使用api的用法，现在应该已经可以正常在firefox使用，两位有兴趣可以帮忙验证下么？

![ScreenShot_2024-05-31_13-14-45](https://github.com/opennaslab/kubespider/assets/47053686/032cfd92-7aec-42ac-91ae-8493bbeca659)

![ScreenShot_2024-05-31_13-14-41](https://github.com/opennaslab/kubespider/assets/47053686/ada509e7-9c24-4a1b-9f5e-9a53dfcc0e2d)

![ScreenShot_2024-05-31_13-14-32](https://github.com/opennaslab/kubespider/assets/47053686/0e5a664e-ac9b-4e5c-af45-0b26dbe485f2)


目前测试情况，不再会Content-Security-Policy强制转为https。能通过healthz。正常存储，和连接。
发送至下载我还没试就是。不过按理来说能过CSP，应该问题不大。

对了，顺带说一句，不知道是我clone下来的原因windows自动给我转了还是项目上Dockerfile文件本身的原因，扒下来格式是，CR LF，不是LF的。当时没注意，生成docker的时候启动不了，hhhhhhh

插件已经生成在我repositories里的firefox-extension文件夹里

Docker在https://hub.docker.com/r/manduted/kubespider-pre

**Comment by manduted** [comment]
@qingchoulove 测试没有问题，docker、Firefox均正常工作
