### ISSUE TITLE
I have some trouble

### ISSUE THREAD

**Issue by childeyouyu** [opennaslab/kubespider#535]
## Ask your question here:

After install it,show the error and I　cannt open the web.
![image](https://github.com/user-attachments/assets/fec70cc7-6631-4d12-bb4c-103f12640717)
![image](https://github.com/user-attachments/assets/ed9c26fe-5b52-426c-b80a-9290048c1a28)

**Comment by miRemid** [comment]
current kubespider is a non-webui application.

**Comment by childeyouyu** [comment]
I will read the usage again.
