### ISSUE TITLE
Chrome插件使用问题

### ISSUE THREAD

**Issue by xiaolx1** [opennaslab/kubespider#547]
按照官方文档正常部署后均能够正常使用，今天发现插件出现问题，SERVER信息可saved，也可refresh successed，但是无法进行下载任务，无论是右键send to kubespider还是通过插件url下载都没有反应。重新安装插件，重启容器问题依旧。

插件错误信息：
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.

Refused to load the script 'chrome-extension://744b53a5-d975-41d2-8307-76056563b6e5/assets/chunk-CBVaWBKk.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

kubespider日志一切正常，没有错误信息。

**Comment by qingchoulove** [comment]
非常感谢，能麻烦提供下chrome版本么？我排查下是否有新的安全策略变更 @xiaolx1

**Comment by xiaolx1** [comment]
> 非常感谢，能麻烦提供下chrome版本么？我排查下是否有新的安全策略变更 @xiaolx1

谢谢回复。
Chrome 已是最新版本
版本 130.0.6723.70（正式版本） （64 位）

**Comment by xiaolx1** [comment]
谢谢辛勤的付出，静候更新

**Comment by qingchoulove** [comment]
因为 chromium 认为这是一个预期外的问题，并已经做出修复。 [
Blocked: `import` path in a content script when `use_dynamic_url` is true](https://issues.chromium.org/issues/363027634?pli=1)。所以本次使用一个临时方案，并保持观察，决定最终是否进行其他修正。@xiaolx1

**Comment by xiaolx1** [comment]
已恢复正常，感谢

**Comment by xiaolx1** [comment]
已恢复正常，感谢
