### ISSUE TITLE
能否支持通用RSS订阅源

### ISSUE THREAD

**Issue by ijwstl** [opennaslab/kubespider#86]
目前通过开发者手动适配资源难免会存在资源不够多不够广的问题，如果能适配rss订阅源，那么就可以获得广泛的资源支持。例如群晖的download station或者asustor的download center一样，可以让用户自主添加想要的rss订阅，并且可以设定资源刷新时间自主下载。
![image](https://user-images.githubusercontent.com/71215012/231771383-db9113c0-04db-4462-9fc1-0feb2c65beac.png)

![image](https://user-images.githubusercontent.com/71215012/231771215-120879a0-8bb6-4500-9c18-29ed7a7b8d83.png)

**Comment by ijwstl** [comment]
订阅源可以通过向本地部署的RSS-HUB发送请求获取，用户手动配置进去，RSS-HUB文档在此https://docs.rsshub.app/。可以设置通用的rss source provider，其中目前provider的接口内容有部分字段需要用户手动配置，例如file_type，需要用户根据自己设定的rss资源类型进行变更。至于执行频次的用户配置可以使用flask_apscheduler，设定最小更新为1h，循环检测用户配置的rss内容，通过check_time和exec_time判断本次定时任务该rss配置是否需要激活，若该配置为一次性类型，这执行过一次后，将状态改为close，下次定时任务执行时则不会激活该项配置。

**Comment by jwcesign** [comment]
> 至于执行频次的用户配置可以使用flask_apscheduler，设定最小更新为1h，循环检测用户配置的rss内容，通过check_time和exec_time判断本次定时任务该rss配置是否需要激活，若该配置为一次性类型，这执行过一次后，将状态改为close，下次定时任务执行时则不会激活该项配置。

这个Kubespider原生有1h的轮转周期，应该能处理这种情况

**Comment by jwcesign** [comment]
@miRemid 大佬有时间也看看

**Comment by xiaozhikang0916** [comment]
其实就是相当于增加一个通用的rss provider，然后依靠RSSHub转换各种线上资源为通用rss格式了

**Comment by jwcesign** [comment]
@xiaozhikang0916 嗯嗯，感觉这个点子挺好的

**Comment by miRemid** [comment]
> @miRemid 大佬有时间也看看

我应该没那么多时间了，现在太忙了😥

**Comment by jwcesign** [comment]
@ijwstl 他实现，我看他已经在搞了，哈哈，就评估一下

**Comment by xiaozhikang0916** [comment]
我只希望不要跟指定下载源的issue冲突太多😥
